server:
  port:

log:
  level: debug

spring:
  datasource:
    url:
    username:
    password:

#=================================redis配置=================================
  redis:
    #地址
    host:
    #端口
    port:
    # Redis数据库索引（默认为0）
    database:
    #Login password
    password:
    #Read timeout
    timeout:
    #connect timeout
    connect-timeout:
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        min-idle:
        # 连接池中的最大空闲连接
        max-idle:
        # 连接池的最大数据库连接数（使用负值表示没有限制）
        max-active:
        #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: