server:
  port: 8082

log:
  level: debug

spring:
  datasource:
    # jdbc:mysql://121.43.63.109:3028/spring_bingo?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&&serverTimezone=Asia/Shanghai
    # useSSL=false 显式设置
    url: jdbc:mysql://121.43.63.109:3028/spring_bingo?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=Asia/Shanghai
    username: bingo
    password: knxzvu213

#=================================redis配置=================================
  redis:
    #地址
    host: 121.43.63.109
    #端口
    port: 6209
    # Redis数据库索引（默认为0）
    database: 0
    #Login password
    password: zcs*-p/v
    #Read timeout
    timeout: 3s
    #connect timeout
    connect-timeout: 10s
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池的最大数据库连接数（使用负值表示没有限制）
        max-active: 8
        #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms